// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBddkbj-hPocZa1l8LWIsiKsYIUG4RL3Y4',
    appId: '1:199654156773:web:8f32f24d189420ba45a70c',
    messagingSenderId: '199654156773',
    projectId: 'fitmax-c4791',
    authDomain: 'fitmax-c4791.firebaseapp.com',
    storageBucket: 'fitmax-c4791.appspot.com',
    measurementId: 'G-NPZ2HMT44V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_B2nLFAAqw6xdcX-Ihpu9esOaG2m_MX4',
    appId: '1:199654156773:android:dd73a0abea7bd3ce45a70c',
    messagingSenderId: '199654156773',
    projectId: 'fitmax-c4791',
    storageBucket: 'fitmax-c4791.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbuFXIp-WqUSZQZUNOjx85MnLCmMr7sJg',
    appId: '1:199654156773:ios:f5613e352577f65645a70c',
    messagingSenderId: '199654156773',
    projectId: 'fitmax-c4791',
    storageBucket: 'fitmax-c4791.appspot.com',
    iosBundleId: 'com.example.sampleLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbuFXIp-WqUSZQZUNOjx85MnLCmMr7sJg',
    appId: '1:199654156773:ios:72067a2ffde034ee45a70c',
    messagingSenderId: '199654156773',
    projectId: 'fitmax-c4791',
    storageBucket: 'fitmax-c4791.appspot.com',
    iosBundleId: 'com.example.sampleLogin.RunnerTests',
  );
}
